#include "F28x_Project.h"
#include "bsp.h"
#include "variable.h"

// Up-down mode: 100 MHz / (2 * 2500) = 20 kHz switching frequency.
#define EPWM3_PERIOD_TICKS    2500U
// One TBCLK is 10 ns, so 100 ticks gives 1 us dead time on both edges.
#define EPWM3_DEADBAND_TICKS   100U
#define EPWM_AQ_FORCE_DISABLED   0U
#define EPWM_AQ_FORCE_LOW        1U
#define EPWM_AQ_FORCE_IMMEDIATE  3U

static volatile Uint16 EPWM3_TripZoneFaulted = 0U;

void EPWM_Config(void)
{
    EALLOW;

    // SYSCLK is 200 MHz. EPWMCLK is divided by 2 to obtain 100 MHz TBCLK.
    CpuSysRegs.PCLKCR0.bit.TBCLKSYNC = 0;//关闭所有 ePWM 模块的时基时钟同步。
    ClkCfgRegs.PERCLKDIVSEL.bit.EPWMCLKDIV = 1;//后续没有额外分频，所以 TBCLK 也是 100 MHz：

    // Center-aligned time base with shadow-loaded period and compare values.
    EPwm3Regs.TBCTL.all = 0;//先清空 EPWM3时基控制寄存器
    EPwm3Regs.TBCTL.bit.CTRMODE = TB_COUNT_UPDOWN;//设置为增减计数模式：0 → 2500 → 0 → 2500 → 0
    EPwm3Regs.TBCTL.bit.PHSEN = TB_DISABLE;//不进行相位同步
    EPwm3Regs.TBCTL.bit.PRDLD = TB_SHADOW;//使用影子寄存器,其实用处不大,又不变频
    EPwm3Regs.TBCTL.bit.HSPCLKDIV = TB_DIV1;//不分100Mhz的频
    EPwm3Regs.TBCTL.bit.CLKDIV = TB_DIV1;   //不分100Mhz的频
    EPwm3Regs.TBCTL.bit.FREE_SOFT = 2;//配置仿真暂停行为。
    EPwm3Regs.TBPRD = EPWM3_PERIOD_TICKS;//100 MHz / (2 × 2500) = 20 kHz
    EPwm3Regs.TBPHS.all = 0;//相位寄存器清零
    EPwm3Regs.TBCTR = 0;//把计数器初始值设为 0

    EPwm3Regs.CMPCTL.all = 0;//清空比较控制寄存器
    EPwm3Regs.CMPCTL.bit.SHDWAMODE = CC_SHADOW;//CMPA 使用影子寄存器
    EPwm3Regs.CMPCTL.bit.LOADAMODE = CC_CTR_ZERO;//波谷装载
    EPwm3Regs.CMPA.bit.CMPA = EPWM3_PERIOD_TICKS / 2U;

    // EPWM3A is the dead-band source; EPWM3B is generated by the DB module.
    EPwm3Regs.AQCTLA.all = 0;//清空 EPWM3A 的动作限定配置。
    EPwm3Regs.AQCTLA.bit.CAU = AQ_CLEAR;//计数器向上计数并遇到 CMPA 时，将 EPWM3A 清零。
    EPwm3Regs.AQCTLA.bit.CAD = AQ_SET;//计数器向下计数并遇到 CMPA 时，将 EPWM3A 置高
    EPwm3Regs.AQCTLB.all = 0;//清空 EPWM3B 的动作限定配置。
    EPwm3Regs.AQSFRC.bit.RLDCSF = EPWM_AQ_FORCE_IMMEDIATE;//将连续软件强制 AQCSFRC配置为立即生效,为之后的disable铺垫
    EPwm3Regs.AQCSFRC.all = 0;//清空 EPWM3B 的 AQ 动作。因为此时PWMB是由PWMA互补得到的

    // Derive active-high complementary outputs from EPWM3A with 1 us dead time.
    EPwm3Regs.DBCTL.all = 0;//清空 Dead-Band 控制寄存器
    EPwm3Regs.DBCTL.bit.OUT_MODE = DB_FULL_ENABLE;//同时启用上升沿延迟 RED 和下降沿延迟 FED。
    EPwm3Regs.DBCTL.bit.POLSEL = DB_ACTV_HIC;//选择高电平有效的互补输出模式。
    EPwm3Regs.DBCTL.bit.IN_MODE = DBA_ALL;//Dead-Band 的 RED 和 FED 两条路径都以 EPWM3A为输入。和上面的PWMB不配置呼应了
    EPwm3Regs.DBRED.bit.DBRED = EPWM3_DEADBAND_TICKS;//上升沿和下降沿死区都设置为 100 TBCLK： 
    EPwm3Regs.DBFED.bit.DBFED = EPWM3_DEADBAND_TICKS;//也就是1us

    // Configure TZ1 as a one-shot shutdown source for both complementary outputs.
    // An external comparator, GPIO/X-BAR route, or software force can assert TZ1.
    EPwm3Regs.TZSEL.bit.OSHT1 = 1U;
    EPwm3Regs.TZCTL.bit.TZA = TZ_FORCE_LO;
    EPwm3Regs.TZCTL.bit.TZB = TZ_FORCE_LO;
    EPwm3Regs.TZEINT.bit.OST = 1U;
    EPwm3Regs.TZCLR.bit.OST = 1U;
    EPwm3Regs.TZCLR.bit.INT = 1U;

    // EPWM3 TZ is PIE group 2, interrupt channel 3.
    PieVectTable.EPWM3_TZ_INT = &EPWM3_TZ_BSP_ISR;
    PieCtrlRegs.PIEIER2.bit.INTx3 = 1U;
    IER |= M_INT2;

    // Trigger ADCA SOC0 once at the end/start boundary of every PWM period.
    EPwm3Regs.ETSEL.bit.SOCAEN = 0;//配置触发源之前，暂时关闭 EPWM3 SOCA。
    EPwm3Regs.ETSEL.bit.SOCASEL = ET_CTR_ZERO;//选择计数器到零作为 SOCA 触发事件。
    EPwm3Regs.ETPS.bit.SOCAPRD = ET_1ST;//每次满足 CTR = 0条件时都产生 SOCA，不进行事件分频。
    //什么两者配合可以产生多种触发周期
    EPwm3Regs.ETCLR.bit.SOCA = 1;//清除可能残留的 SOCA 事件标志，保证第一次触发从干净状态开始。
    EPwm3Regs.ETSEL.bit.SOCAEN = 1;//正式允许 EPWM3产生 SOCA。

    EDIS;
}

void EPWM_Start(void)
{
    // GPIO muxing and ADC setup are complete before synchronized counting starts.
    EALLOW;
    CpuSysRegs.PCLKCR0.bit.TBCLKSYNC = 1;//给心跳所有计数器开始启动
    EDIS;
}

void EPWM_Disable(void)
{
    EALLOW;

    // DB normally derives complementary B from A, so bypass it before forcing
    // both raw AQ outputs low. The time base and ADC SOCA keep running.
    EPwm3Regs.DBCTL.bit.OUT_MODE = DB_DISABLE;//死区模块旁路
    EPwm3Regs.AQCSFRC.bit.CSFA = EPWM_AQ_FORCE_LOW;//A通道强制置0
    EPwm3Regs.AQCSFRC.bit.CSFB = EPWM_AQ_FORCE_LOW;//B通道强制置0

    EDIS;
}

void EPWM_Enable(void)
{
    EALLOW;

    // Clear a previous one-shot trip before allowing PWM outputs to resume.
    EPwm3Regs.TZCLR.bit.OST = 1U;
    EPwm3Regs.TZCLR.bit.INT = 1U;
    EPWM3_TripZoneFaulted = 0U;
    gMachineData.tripZoneFaulted = 0U;

    // Restore dead-band before releasing AQ so complementary switching always
    // resumes through the configured 1 us non-overlap interval.
    EPwm3Regs.DBCTL.bit.OUT_MODE = DB_FULL_ENABLE;
    EPwm3Regs.AQCSFRC.bit.CSFA = EPWM_AQ_FORCE_DISABLED;
    EPwm3Regs.AQCSFRC.bit.CSFB = EPWM_AQ_FORCE_DISABLED;

    EDIS;
}

void EPWM_TripZoneForce(void)
{
    EALLOW;

    // Software test path: latch the same one-shot trip as an external TZ1 event.
    EPwm3Regs.TZFRC.bit.OST = 1U;

    EDIS;
}

void EPWM_TripZoneClear(void)
{
    EALLOW;

    // Clear the one-shot latch; outputs remain under normal AQ/dead-band control.
    EPwm3Regs.TZCLR.bit.OST = 1U;
    EPwm3Regs.TZCLR.bit.INT = 1U;
    EPWM3_TripZoneFaulted = 0U;
    gMachineData.tripZoneFaulted = 0U;

    EDIS;
}

__interrupt void EPWM3_TZ_BSP_ISR(void)
{
    // Record the fault and clear only the interrupt request. Keep OST latched
    // so the PWM outputs remain forced low until software explicitly clears it.
    EPWM3_TripZoneFaulted = 1U;
    gMachineData.tripZoneFaulted = 1U;
    EPwm3Regs.TZCLR.bit.INT = 1U;
    PieCtrlRegs.PIEACK.all = PIEACK_GROUP2;
}

void EPWM_SetDuty(float duty)
{
    // Preserve a minimum on/off interval for dead-band and future gate drivers.
    if(duty < 0.02f)
    {
        duty = 0.02f;
    }
    else if(duty > 0.98f)
    {
        duty = 0.98f;
    }

    EPwm3Regs.CMPA.bit.CMPA = (Uint16)(duty * (float)EPWM3_PERIOD_TICKS);
}
